### PR TITLE
Add aarch64-unknown-linux-gnu support

### PR DESCRIPTION
**Pull request by Nehliin**
Tested on Ampere Altra Arm64. Added extra run script since we already have a separate for android (this needs `-fsigned-char`) and didn't want to over compilcate the bash scripts

follow up of: https://github.com/EmbarkStudios/physx-rs/pull/153

### CODE REVIEW

**Review by Jake-Shadle — APPROVED** [review]

**Comment by Jake-Shadle** [comment]
Should add a build test to the CI for this target since it is distinct from both x86_64 linux and aarch64 android.

**Comment by Nehliin** [comment]
Not sure how to actually test the new workflows pre merge, tried act but that couldn't even run the rustup action

**Comment by Jake-Shadle** [comment]
FYI https://github.com/actions/virtual-environments/issues/5930 for the android failure

**Comment by Nehliin** [comment]
Should be fixed by this: https://github.com/EmbarkStudios/physx-rs/pull/155 (debug build just passed, just had to update release builds to match it)

**Pull request merged**
