### PR TITLE
Upgrade glam to 0.9

### PR DESCRIPTION
**Pull request by hrydgard**
Replaces #71 .

Before we merge this, I'll patch my local ark to use this and test that it works.

### CODE REVIEW

**Comment by hrydgard** [comment]
It works.

**Comment by hrydgard** [comment]
Done, I think we'll need to bump the "major" version btw...

**Comment by repi** [comment]
Yeah has to be a major version as the glam types are part of the public API

**Comment by hrydgard** [comment]
@repi This needs another approval to merge now

**Pull request merged**
