### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by MaikKlein**

### CODE REVIEW

**Comment by repi** [comment]
Oh looks like `cmake` is not installed? That is a bit odd

**Comment by MaikKlein** [comment]
Yeah weird. It lists cmake here https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts

**Comment by MaikKlein** [comment]
Oh wait it just doesn't fine the cmake file which probably means build.rs doesn't do a submodule clone.

**Comment by MaikKlein** [comment]
Now the build only fails for windows. I am not quite sure why though.

**Comment by MaikKlein** [comment]
Seems like typeinfo got removed in the newest vs compiler :(. https://developercommunity.visualstudio.com/content/problem/734566/msvc-142328019-is-missing-include-typeinfoh.html

**Comment by Jake-Shadle** [comment]
You probably want to remove the travis tests/lints as well.

**Pull request merged**
