### PR TITLE
Add Windows  2019 / Visual Studio 2019 CI build

### PR DESCRIPTION
**Pull request by repi**

### CODE REVIEW

**Comment by repi** [comment]
2019 build is failing as we expected, we should try and solve it.

Related issue on the physx repo: 
https://github.com/NVIDIAGameWorks/PhysX/pull/181
https://github.com/NVIDIAGameWorks/PhysX/issues/164

**Comment by repi** [comment]
Hmm thought my hack `typeinfo.h` include would work, but doesn't. @hrydgard could you try later and test on your Windows machine? rather slow to iterate over CI and I'm out of ideas right now

**Comment by repi** [comment]
@h3r2tic can you figure out a solution here?

**Comment by h3r2tic** [comment]
I'm looking into it now.

**Comment by h3r2tic** [comment]
Resolved by #37

**Pull request closed without merging**
