### PR TITLE
Add project maintainers as codeowners

### PR DESCRIPTION
**Pull request by lpil**
We are making our open source project maintainers explicit with a CODEOWNERS file. Let me know /f these are not the correct maintainers for this project

### CODE REVIEW

**Comment by h3r2tic** [comment]
I haven't been maintaining this project for a while, and I'm afraid I can't really allocate the time.

(Huge thanks to all the other contributors for picking up the ball (.rs) that I dropped)

**Comment by lpil** [comment]
Sure thing, I just got this from the existing list of maintainers which is outdated. Who should be the maintainer now?

**Comment by VZout** [comment]
@hrydgard Might make sense? (Sorry for throwing you under the bus Henrik)

**Comment by lpil** [comment]
I've updated this now, let me know if this is good to merge. Thanks

**Comment by lpil** [comment]
This this waiting on anything in particular?

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
I think it just drowned in a flood of issues.

**Comment by lpil** [comment]
Always the way! Thank you

**Pull request merged**
