### PR TITLE
Update glam to 0.12

### PR DESCRIPTION
**Pull request by XAMPPRocky**

### CODE REVIEW

**Comment by hrydgard** [comment]
Oh great, CI chokes on that alloca problem. @tgolsson what do we do about that?

**Comment by tgolsson** [comment]
@hrydgard Can we pass in `-Wno-alloca` to the CMake builder?

**Comment by hrydgard** [comment]
Yeah, we probably can somehow. @XAMPPRocky probably knows how ...

**Comment by XAMPPRocky** [comment]
Provided this is the right place it should just be adding `cflag`.

https://github.com/EmbarkStudios/physx-rs/blob/4c5cc557c518a092cf6fca8001c763692ac469db/physx-sys/cmake.rs#L143

**Comment by XAMPPRocky** [comment]
It was `cxxflag`, but it solved that error. The next one is the following. Do we just want to add `-Wanon-enum-enum-conversion`?

```
  In file included from /home/runner/work/physx-rs/physx-rs/physx-sys/PhysX/physx/source/scenequery/src/SqBounds.cpp:35:
117
  /home/runner/work/physx-rs/physx-rs/physx-sys/PhysX/physx/source/physx/src/buffering/ScbActor.h:191:32: error: bitwise operation between different enumeration types ('physx::Scb::ActorBuffer::(anonymous enum at /home/runner/work/physx-rs/physx-rs/physx-sys/PhysX/physx/source/physx/src/buffering/ScbActor.h:56:2)' and 'physx::Scb::ActorBuffer::(anonymous enum at /home/runner/work/physx-rs/physx-rs/physx-sys/PhysX/physx/source/physx/src/buffering/ScbActor.h:57:2)') [-Werror,-Wanon-enum-enum-conversion]
118
          if(flags & (Buf::BF_ActorFlags|Buf::BF_DominanceGroup/*|Buf::BF_ClientBehaviorFlags*/))
119
                      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by hrydgard** [comment]
Yeah, I think that's fine

**Comment by hrydgard** [comment]
I think you need -Wno-anon.... instead of -Wanon....

**Comment by XAMPPRocky** [comment]
Seems like everything passes now.

**Review by hrydgard — APPROVED** [review]

**Review by tgolsson — APPROVED** [review]

**Pull request merged**
